# Handling reading
exclude:
  - README.md
  - LICENSE
  - CNAME
  - Gemfile
encoding: "utf-8"

# Plugins
gems:
  - jemoji
  - jekyll-mentions
  - jekyll-redirect-from
  - jekyll-sitemap

# Conversion
markdown: kramdown

# Outputting
timezone: Asia/Kathmandu
locale: en_us

# URL of site, include http://, do not include a trailing slash
url: "https://kshitizaryal.github.io"

# Site settings
title: Kshitiz Aryal
description: "Follow Kshitiz Aryal across the interwebs."
icon: "/assets/img/k-icon-white-on-teal.png"

social:
  - title: Twitter
    url: https://twitter.com/KshitizAryal
    fa: twitter

  - title: Facebook
    url: https://www.facebook.com/kshitiz.aryal
    fa: facebook

  - title: Instagram
    url: https://instragram.com/considerkshitiz
    fa: instagram

  - title: Tumblr
    url: http://kshitizaryal.tumblr.com
    fa: tumblr

# Google Maps API Key and local location
google_map:
  api: "AIzaSyBRfaWsUPFLarp7efMqyne-1K7uigYPtyQ"
  zoom: 13
  latitude: "27.7089603"
  longitude: "85.3261328"

# Compress HTML
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
